#!/bin/bash
#
# $Id$
#
# Icetray environment script.
#
# THIS FILE WAS AUTOGENERATED.  ANY CHANGES YOU MAKE HERE WILL BE
# LOST.  
# 
# [tds] If you need to change things here to make things work, that's
# a bug and you should *report* this to dataclass@icecube.wisc.edu or
# offlinebug@icecube.umd.edu.  Thanks for your help.  
#
if [[ -z "$I3PROD" ]] 
    then
	echo "You must define I3PROD in your environment."
	exit
	fi

if [[ "$1" = "help" ]]
    then
    echo "Usage: $0 [SHELL]"
    echo "Spawn a new shell with an Icetray environment loaded"
    echo ""
    echo "SHELL can specified with or without a full path.  If SHELL"
    echo "is omitted the login shell is used by default."
    echo "Examples:"
    echo "   ./env.sh"
    echo "   ./env.sh tcsh"
    echo "   ./env.sh /bin/tcsh"
    echo ""
    echo "To exit the Icetray environment simply exit the new shell."
    echo ""
    exit 1
fi

if [[ -z "$1" ]]
    then # user did not specify a shell
    NEW_SHELL=$SHELL 
    # only exit if no shell specified on command line *and* env already loaded 
    if [[ -n "$I3_SHELL" ]] 
	then  
	echo "****************************************************************"
	echo "You are currently in a shell with an Icetray environment loaded."
	echo "Please exit the current shell and re-run $0 from a clean shell."
	echo "****************************************************************"
	echo "Environment not (re)loaded."
	exit 2
    fi
else
    NEW_SHELL=$1
    shift
    ARGV=$*
fi

_I3_SHELL=$NEW_SHELL

_I3_PORTS=$I3_PORTS
_I3_BUILD=$I3PROD
_I3_SRC=$I3_BUILD/projects
_I3_WORK=$I3_BUILD/projects

_LD_LIBRARY_PATH=$I3_BUILD/lib:$I3_BUILD/lib/tools:$I3_PORTS/lib:$I3_PORTS/root-v5.10.00/lib:$LD_LIBRARY_PATH
_DYLD_LIBRARY_PATH==$I3_BUILD/lib:$I3_BUILD/lib/tools:$I3_PORTS/lib:$DYLD_LIBRARY_PATH
_PYTHONPATH=$I3_BUILD/lib:$I3_BUILD/lib/tools:$I3_BUILD/lib/python:$I3_BUILD/lib/python/site-packages:$I3_PORTS/root-v5.10.00/lib:$PYTHONPATH
_PATH=/home/juancarlos/icecube/icetray/iceprod/trunk/build/bin:$_I3_PORTS/bin:/opt/icecube/tools/i3ports/RHEL4-x86_64/root-v5.10.00/bin:$PATH

TOPBAR="************************************************************************"
WIDTH=`echo "$TOPBAR" | wc -c`

WIDTH=$(( $WIDTH-2 ))

function printctr()
{
    LEN=`echo "$*" | wc -c`
    LOFFSET=$(( ($WIDTH-$LEN)/2 ))
    ROFFSET=$(( $WIDTH-$LOFFSET-$LEN ))

    FORMAT="*%${LOFFSET}s%s%${ROFFSET}s*\n"
    printf $FORMAT " " "$*" " "
}

if [[ -z "$ARGV" ]]
    then
    printf "$TOPBAR\n"
    printctr ""
    printctr "W E L C O M E  to  I C E T R A Y"
    printctr ""
    printctr "Version @META_PROJECT@     r@SVN_REVISION@"
    printctr ""
    printctr "You are welcome to visit our Web site"
    printctr "http://icecube.umd.edu"
    printctr ""
    printf "$TOPBAR\n"
    printf "\n"
    printf "Icetray environment has:\n"
    printf "   I3_SRC       = %s\n" $_I3_SRC
    printf "   I3_BUILD     = %s\n" $_I3_BUILD
    printf "   I3_PORTS     = %s\n" $_I3_PORTS
fi

if [[ -z "$I3_SHELL" ]] # a clean, first invocation
    then

    PATH=$_PATH \
	LD_LIBRARY_PATH=$_LD_LIBRARY_PATH \
	DYLD_LIBRARY_PATH=$_DYLD_LIBRARY_PATH \
	PYTHONPATH=$_PYTHONPATH \
	ICETRAY_CLASSPATH=$_ICETRAY_CLASSPATH \
        I3_PLATFORM="" \
	I3_WORK=$_I3_WORK \
	I3_SRC=$_I3_SRC \
	I3_BUILD=$_I3_BUILD \
	I3_PORTS=$_I3_PORTS \
	I3_TOOLS=$I3_PORTS \
	ROOTSYS=$I3_PORTS/root-v5.10.00 \
	I3_SHELL=$_I3_SHELL \
	$NEW_SHELL $ARGV

else  # not clean, use previous environment
    $NEW_SHELL $ARGV
fi

STATUS=$?

if [ -z "$ARGV" ]
then
    echo "Exited Icetray Environment."
fi
exit $STATUS
