# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python tests

on:
  pull_request:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo:3.6
        ports:
        - 27017:27017
    env:
      TEST_DATABASE_URL: "localhost:27017"
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      id: dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests
      run: |
        ./coverage.sh
    - name: Lint with flake8
      if: always() && steps.dependencies.outcome != 'failure'
      run: |
        flake8 iceprod --count --show-source --statistics
    - name: Coverage report
      if: always() && steps.dependencies.outcome != 'failure'
      run: |
        coverage report -m --fail-under=50
